### ISSUE TITLE
Why I’m not answering the CMU Delphi survey on Facebook

### ISSUE THREAD

**Issue by elvey** [cmu-delphi/delphi-epidata#116]
I appreciate what you’ve done and continue to do in epi-forecasting. But it seems to me like the problem in front of us is not so much lack of information as is it is lack of spine.  I think epidemiologists need to join together and say  that we’re (our governments are) doing the exact worst thing. I mean is there an  epidemiologists out there who thinks that the current approach is appropriate? It seems to me like anyone with expertise and foresight must believe that we’re either doing too much or not enough, and the shift in either direction would be better than the status quo.  

What’s the plan?  
•••••••••••••••••
Plan? MY view: We MUST either step up and tighten (w/quarantines AND/or testing) our state and/or country borders AND get serious about tracing AND other steps to *wipe it out* OR allow a controlled spread, by unlocking, from youngest to oldest as that is the fastest approach to restoring some kind of normality. politician approval rates are terrible for good reason. I HATE our empowered politicians, who are (AFAIK) ALL too spineless to do anything but think unbelievably short term. So we’ve got the worst of both worlds. We’re not wiping out the virus AND we’re destroying the economy.  We’re doing the one thing stupider than opening up the economy further, which is not tightening it up enough to wipe out the virus and keep it out. As Mr. Rogers, said I’m so angry I could bite. I don’t hear anybody asking our president or governor or mayor what the long-term plan is!!! We/ Our media must ASK them and more and demand answers and report!  Leaders and health officials seem too ignorant or power-hungry to understand how a privacy-preserving app could be very effective; their myopia is maddening! 

Please forgive me if i’m  unable to keep entirely to the issue system guidelines a wee bit here. I just had to get this off my chest. No I’ve never done this before, and expect I won’t again. Crazy times. You can just close this. Please don’t delete it. Or do, but a friendly word would really mean a lot right now. Thanks 🙏.

**Comment by krivard** [comment]
Hi elvey, thank you for your thoughtful message. Fortunately, there are a large number of people working to support humanity in the pandemic, so collectively, we're not limited to working on one thing at a time. Our group has expertise in statistical modeling, so that's how we're best equipped to contribute. I think you recognize that a data API cannot provide the primary thrust toward increased testing, tracing, and isolation. We do however aim to provide crucial evidence in the arguments that support these policies and inform how, where, and when they are rolled out. I urge you to contact your representatives, not just in D.C. but the people making decisions on state, county, and city levels as well, so that they know that they have your support. Government is constantly trying to strike a balance between what will keep people safe, and what people will not accept -- the reopen protests are a signal that they are already close to the line. If you can make it clear that you are keeping your local community of friends, family, neighbors, and coworkers accountable, policymakers will be more free to do what is needed.
