### ISSUE TITLE
Consider adding support for 'group_by' in COVIDcast queries

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#173]
The [proposed tree format for multi-signal queries](https://github.com/cmu-delphi/delphi-epidata/pull/170) is really a group-by. We should consider permitting a group_by parameter that would generate this structure for any parameter that accepts multiple values (time_value certainly; geo_value might hurt).

**Comment by sgratzl** [comment]
should the group by mode be just one level or multiple ones? what should the parameter be called which controls it?

**Comment by sgratzl** [comment]
in general: I'm not sure whether returning a more complex tree structure is useful, since it makes further processing with standard data science tools (like data frames) more difficult. On the client side, methods like https://github.com/d3/d3-array/blob/master/README.md#group can be used to achieve a similar effect.

**Comment by krivard** [comment]
That makes sense. iirc the original groupby/tree structure was the preference of @rhansolo and @lxieyang for multi-signal queries. Since there's a way to do it client side, there's no reason to do it here.
