### ISSUE TITLE
consider adding support for ISO date format: yyyy-mm-dd

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#180]
it is is a common format for defining date data both for parameters and return values.

**Comment by sgratzl** [comment]
to discuss if we want to support the new date format:

 * for ranges also a `-` dash is used. Thus a range with this iso format is difficult. it would be `2020-01-05-2020-02-07`
 * if we want to change the return date format, we would need a new parameter: which name?

**Comment by krivard** [comment]
`yyyy-mm-dd:yyyy-mm-dd` is probably suitable for ISO ranges, and we should enforce that each individual query use either all-ISO or all-integer dates so that the parse logic is simpler.

The clients handle parsing the return dates into datetimes, so there's no need to handle that at the server level.
