### ISSUE TITLE
Consider adding COVIDcast support for HHS regions

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#192]
Currently, [data ingestion accepts](https://github.com/cmu-delphi/delphi-epidata/blob/dff64d0822159ed1d321256414112e9715b71bdb/src/acquisition/covidcast/csv_importer.py#L27) the following geographical types:
* county
* hrr
* msa
* dma
* state

We currently have [an indicator waiting in the wings](https://github.com/cmu-delphi/covidcast-indicators/tree/main/cdc_covidnet) whose ideal geographical type is HHS region. To begin serving it from the API, ingestion needs to know how to validate HHS region ids.

Further reading:
* [Health & Human Services Regions](https://www.hhs.gov/about/agencies/iea/regional-offices/index.html)
* Coordinate with [HHS support in the geo mapper](https://github.com/cmu-delphi/covidcast-indicators/pull/217)

**Comment by dfarrow0** [comment]
Lots of the flu work involves HHS and Census regions. See https://github.com/cmu-delphi/utils/blob/main/src/geo/locations.py

Regions are nice to work with because they're just sets of states. If you have a signal at the state level, it's trivial to aggregate it up to the HHS or Census level.

The epidata API defines the following region ids: https://github.com/cmu-delphi/delphi-epidata/blob/main/labels/regions.txt

---

@krivard is this issue the only thing blocking the covidnet source?

**Comment by krivard** [comment]
>  If you have a signal at the state level, it's trivial to aggregate it up to the HHS or Census level.

Just to clarify, aggregation does not happen in this codebase; this ticket is solely about supporting HHS region ids [during COVIDcast acquisition](https://github.com/cmu-delphi/delphi-epidata/blob/af77e81cf47f8fa9d88a64fe72d0fc3db8bde4ab/src/acquisition/covidcast/csv_importer.py#L221) and adding associated tests.

@dfarrow0 No; I've written up the remaining COVIDnet work in [a new issue](https://github.com/cmu-delphi/covidcast-indicators/issues/296) to avoid confusion with the other CDC hospital data.

**Comment by dshemetov** [comment]
@krivard just ran across this issue. GeoMapper [supports](https://github.com/cmu-delphi/covidcast-indicators/blob/deploy-jhu/_delphi_utils_python/delphi_utils/data/state_code_hhs_region_number_table.csv) `state_code` -> `hhs_region_number` mappings now.

**Comment by sgratzl** [comment]
can we close this?

**Comment by krivard** [comment]
Yep; fixed in #314
