### ISSUE TITLE
consider changing categorical values in db

### ISSUE THREAD

**Issue by melange396** [cmu-delphi/delphi-epidata#257]
the covidcast database columns `source`, `signal`, `time_type`, and `geo_type` (and probably also `geo_value`) are really just categorical variables...  making them ENUMs is not desirable because as we add to each category, the DB would likely thrash as it needs to re-write entire tables.  these are the only VARCHAR columns in our database, and i believe using them to filter queries is expensive because of string comparisons.  making them into 4-5 foreign key tables would reduce the string comparison cost, with the tradeoff of slightly more complicated-looking queries.  i think the real tricky part here will be when adding data with a new instance of some category, which will require lookup and potential additional insert(s) before writing new records -- the high(ish) cardinality of `geo_value` may end up not being worth it.

**Comment by krivard** [comment]
I like this idea in the context of a larger project to shift us to a database abstraction layer (a la #177). It will make direct inspection of the db more difficult, but (1) most of those columns only have a handful of possible values, which is reasonable to either just remember or put on a post-it, and (2) we may be able to lean on whatever visualization system comes with the abstraction layer we choose instead

**Comment by capnrefsmmat** [comment]
I would support having a `covidcast_source` table whose primary key is the tuple `(source, signal, time_type, geo_type)`, with a serial ID. Then each query to `covidcast` just involves filtering on the matching ID, and the metadata table can also be keyed by it.

I also like this because we could use it to store static information about each signal. For example, I think it'd be *really* nice to have the appropriate documentation page for each signal fetchable from the API, so the site and the packages can automatically direct people to that page. That link could go in this table or a connected one.

**Comment by melange396** [comment]
this was ~mostly addressed by our v4 schema changes
