### ISSUE TITLE
add healthdata.gov signals on hospitalizations

### ISSUE THREAD

**Issue by nickreich** [cmu-delphi/delphi-epidata#288]
We are hoping to migrate the teams doing the hospitalization forecasting challenge at the COVID-19 Forecast Hub over to using the datasets recently (in the last few days) made publicly available at the link below.

Note API links on left-hand panel down the page a bit:
https://healthdata.gov/dataset/covid-19-reported-patient-impact-and-hospital-capacity-state-timeseries

**Comment by RoniRos** [comment]
FWIW, Nick just pointed me to [the data dictionary](https://healthdata.gov/covid-19-reported-patient-impact-and-hospital-capacity-state-data-dictionary) for this table.  Worth storing with the metadata,

**Comment by nickreich** [comment]
Note that the most time-sensitive columns of this dataset to be surfacing are

 - `previous_day_admission_pediatric_covid_confirmed` 
 - `previous_day_admission_adult_covid_confirmed `

For Forecast Hub purposes, it may make sense to return the sum of these two values, as this is likely to emerge as the central hospitalization forecast target.

**Comment by dfarrow0** [comment]
Thanks, noted.

It looks like the dataset was updated yesterday (11/18). I have a local version of the previous issue (11/16). When the code gets checked in, I'll manually load the previous issue so that we have a complete revision history in the API.

@nickreich are there versions of this dataset prior to 11/16? if so, do you have them?

**Comment by nickreich** [comment]
I don't know of prior versions. I think there were some available privately within the HHS Protect system, but I don't think they are public.

**Comment by nickreich** [comment]
Thanks @krivard and @dfarrow0. Is there another issue where I can track the progress of adding this to the covidcast system?

**Comment by dfarrow0** [comment]
Quick update: acquisition code has been merged and is scheduled to run twice daily. The data is now available via the Delphi Epidata API directly ([sample URL](https://delphi.cmu.edu/epidata/api.php?source=covid_hosp&states=PA&dates=20201101)), although the PyPI python package hasn't been updated yet — planning to do that tomorrow.

EpiVis, our relatively obscure web visualization for the API, has been updated to support this new dataset. As an example, here's [an interactive plot of inpatient bed utilization over time for ND](https://delphi.cmu.edu/epivis/epivis.html#eyJjaGFydCI6eyJ2aWV3cG9ydCI6WzczNzQzNS4zMDA1NTU2MjYyLC0wLjA1NjIwMjYzNTA4OTI2MTU1LDczNzkwNC43NjEzOTEwMzU3LDEuMDgxODc0MTUwMTY0OTEzMl0sInNob3dQb2ludHMiOmZhbHNlfSwiZGF0YXNldHMiOlt7ImNvbG9yIjoiIzc1ODZkMiIsInRpdGxlIjoiaW5wYXRpZW50X2JlZHNfdXRpbGl6YXRpb24iLCJwYXJlbnRUaXRsZSI6IkNPVklEIEhvc3BpdGFsaXphdGlvbjogTkQgKG1vc3QgcmVjZW50IGlzc3VlKSIsInBhcmFtcyI6WyJjb3ZpZF9ob3NwIiwiTkQiLG51bGxdfV19). Spoiler: it's at 75% and increasing.

**Comment by dfarrow0** [comment]
@nickreich I'll have to defer to @krivard for an ETA on COVIDcast.

But just to clarify, could you elaborate a little bit? For example, are you asking when it'll be available on the map at https://covidcast.cmu.edu/, or when it'll be available though the `covidcast` R package, or something else?

**Comment by RoniRos** [comment]
> EpiVis, our relatively obscure web visualization for the API, has been updated to support this new dataset. 

Hurray, @dfarrow0 !  You must remember how much I love EpiVis!

**Comment by RoniRos** [comment]
@nickreich may revise or elaborate, but for the purpose of the CDC forecasting activity, I think it's more important that this summed-up signal be available in the API, so we can point to it and tell all participants "This signal is to be used as the Ground Truth for hospitalization forecasting".  While we can tell them that the ground truth is the sum of these two already-existing signals, that's kind of clumsy.  
For the purpose of the CDC forecasting activity, I don't think there is a need to add the summed-up signal to the map.  But it might be something we could consider separately.

**Comment by nickreich** [comment]
I agree that for modeling purposes, adding the sum is important to have a single signal for "ground truth".

I don't quite understand the distinction between the Epidata API and being available via the covidcast R package, say. @dfarrow0 that is what I was curious about. I don't care too much about the website availability, but do want to be able to access via an API somehow, and the more smooth that is, the better.

Final question: this weekend they seemed to post an incorrect file and then later corrected it. how does your system handle this?

**Comment by dfarrow0** [comment]
> I don't quite understand the distinction between the Epidata API and being available via the covidcast R package

Yeah this is unclear, and we haven't been very consistent in general about how we refer to these things. The short version is this: the Epidata API contains various "endpoints". For example, `fluview`, `nowcast`, `covid_hosp`, `covidcast`, etc. We have libraries in python, R, javascript called `delphi-epidata`, and those libraries can fetch data from all Epidata API endpoints. Separately, Delphi has much more specialized/powerful libraries in python and R called `covidcast`, and these libraries fetch data solely from the `covidcast` endpoint of the Epidata API. For some time we've loosely called this the "COVIDcast Epidata API" (although IMO that's something of a misnomer since it's not separate API).

In any case, the `covid_hosp` endpoint of the Epidata API hosts this HHS dataset, and so it's not available via the `covidcast` library, but it is available via the `delphi-epidata` library.

> I agree that for modeling purposes, adding the sum is important to have a single signal for "ground truth".

As I understand it, the plan is to compute this sum and surface it via the `covidcast` endpoint, which would make it available in the `covidcast` library. Until then, someone would need to use the generic `delphi-epidata` library and compute the sum manually.

> want to be able to access via an API somehow, and the more smooth that is, the better.

Definitely agree that smoother is better, and currently there's room for improvement. Currently you can access the data with the `delphi-epidata` library, or you can just curl it directly, for example: https://delphi.cmu.edu/epidata/api.php?source=covid_hosp&states=PA&dates=20201101

---

> Final question: this weekend they seemed to post an incorrect file and then later corrected it. how does your system handle this?

The API stores each dataset along with a version number, which we refer to as "issue" (as in "The December _issue_ of Nature magazine"). Anyway, when you query the Epidata API, it returns data from the most recent issue by default. If you request data from a specific issue, it'll return that instead. So when a correction is posted, that becomes the most recent version and will be returned in queries by default.
