### ISSUE TITLE
Mask Wearing Survey Data No Longer Being Collected?

### ISSUE THREAD

**Issue by lcoome** [cmu-delphi/delphi-epidata#430]
What is the status of the mask wearing survey data? The last date that appears to have all the states in the data is Feb 14 - is data collection on this measure going to continue?

**Comment by krivard** [comment]
Thankyou for reporting this issue. The maskwearing survey question received a minor update in [Wave 8](https://cmu-delphi.github.io/delphi-epidata/symptom-survey/coding.html#wave-8), but the change didn't make it into the analysis code, causing our system to mistakenly skip the question. Overlap in respondents between Waves 7 and 8 hid the problem until last Friday, Feb 26. We have a fix that's going into production for tomorrow's run, and we will be reissuing the mask signals for the affected dates once we've verified that the fix is working as expected. We do intend to continue collecting maskwearing data in the near term, though @WichadaLMK may be able to clarify what the long-term plans are for the mask questions.

**Comment by WichadaLMK** [comment]
Thanks for your interest in our survey data and reporting this issue. The masking wearing questions were changed from Wave 7 to Wave 8 to reflect the last 7 days and be consistent with the time reference in other survey questions. We document changes in each wave here: https://cmu-delphi.github.io/delphi-epidata/symptom-survey/coding.html

The data was collected but not updated in the data files and that should be backfilled starting tomorrow. At the moment there are no plans to edit or remove the mask wearing questions in the CMU Delphi's COVID Symptom Survey through Facebook.
