### ISSUE TITLE
doctor-visits smoothed_adj_cli 20210330 gives "no results" response

### ISSUE THREAD

**Issue by lematt1991** [cmu-delphi/delphi-epidata#613]
I'm currently getting `{'result': -2, 'message': 'no results'}` response from the following code:

```python
from delphi_epidata import Epidata
res = Epidata.covidcast("doctor-visits", "smoothed_adj_cli", "day", "state", ["20210330"], "*")
print(res)
```

This works fine if I use "county" instead of "state".  Is this a bug or is this data known to be missing?  It seems that it is only this particular date that is missing for me.  Any help is much appreciated, thanks!

**Comment by lematt1991** [comment]
Hi, I'm seeing this problem again for more recent dates and new sources/signals.  The following script should reproduce the failures I'm seeing:


```Python
from delphi_epidata import Epidata

failures = [
    ('fb-survey', 'smoothed_wcovid_vaccinated_or_accept', '20210625'),
    ('fb-survey', 'smoothed_wcovid_vaccinated_or_accept', '20210625'),
    ('fb-survey', 'smoothed_wothers_masked', '20210624'),
    ('fb-survey', 'smoothed_wothers_masked', '20210625'),
    ('fb-survey', 'smoothed_wothers_masked', '20210626'),
    ('fb-survey', 'smoothed_wothers_masked', '20210624'),
    ('fb-survey', 'smoothed_wothers_masked', '20210625'),
    ('fb-survey', 'smoothed_wothers_masked', '20210626'),
    ('fb-survey', 'smoothed_wcovid_vaccinated_or_accept', '20210625'),
    ('fb-survey', 'smoothed_wcovid_vaccinated_or_accept', '20210625'),

]

for source, signal, date in failures:
    res = Epidata.covidcast(source, signal, "day", "county", [date], "*")
    print(res)
    
```

Maybe this is related to #614?

**Comment by sgratzl** [comment]
related API calls:

* https://api.covidcast.cmu.edu/epidata/covidcast/?signal=fb-survey:smoothed_wcovid_vaccinated_or_accept&geo=county:*&time=day:20210625
* https://api.covidcast.cmu.edu/epidata/covidcast/?signal=fb-survey:smoothed_wothers_masked&geo=county:*&time=day:20210624-20210626

**Comment by krivard** [comment]
Yep, I'm not surprised. We have a script grinding through the fix (exhaustively, for all sources, signals, and dates); I'll post here and close when it's finished.

**Comment by krivard** [comment]
Okay script is done, and the original report on `doctor-visits` has been repaired, as well as a handful of other sources, signals, geos, and dates. However, for the surveys signals you're running into a different problem: Our response rate has been dropping steadily since January, and we don't publish data on any region that contains less than 100 survey responses. Not all respondents answer all of the survey questions, and it looks like we only had 900 or so respondents answer the questions for `smoothed_wcovid_vaccinated_or_accept` on June 25 in the United States. The only state that occasionally meets our sample size thresholds for that signal over the last week is California, which had 111 respondents on the 26th. I'm afraid there's no hope of county data for that signal in the near future.

We're actively thinking about different treatments of the survey data as interest wanes in taking pandemic-flavored surveys, possibly reducing temporal resolution in favor of better spatial resolution (eg expand to include 2 weeks of data or more). Let me know if you're interested in that conversation and I can put you in touch with our survey coordinator.

**Comment by lematt1991** [comment]
Got, thanks for the explanation!
