### ISSUE TITLE
Other Diseases --> Other Endpoints?

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/delphi-epidata#797]
One of the headings in the table of contents on the left in the [Epidata documentation](https://cmu-delphi.github.io/delphi-epidata/api/README.html) says "Epidata API (Other Diseases)".  

I'm not a fan of "Diseases" because there is indeed COVID data here, e.g., all the HHS endpoints. And not every endpoint is its own disease. So how about just "Other Endpoints"? @RoniRos @capnrefsmmat @krivard

**Comment by RoniRos** [comment]
I agree "Other Diseases" is inappropriate, but "Endpoints" isn't ideal either, because I think it is better to describe the content (which is what people are presumably looking for) rather than define it by the access details.

More generally, I find the tree structure confusing.  For example, it implies that CTIS is not part of COVIDcast - is that intended?  

I think the root cause of my confusion is that Diseases, Data Sources and Endpoints don't align neatly.

 - Diseases arguably ought to be the highest-level concept in the tree -- a user coming in knows whether they are interested in Covid, flu, or something else.  They also want to be able to see all the signals related to say, Covid, regardless of which Data Sources or Endpoints they are under.
  - However, many data sources are used for multiple diseases, e.g. Quidel, Google Search, CHNG.
  - I think of Endpoints as "dialects" or sub-versions of the API.  The differences between them is in what arguments they require/accept and what data type(s) they return.  Is this correct?  Unfortunately, these dialects cut across both Diseases and Data Sources.

I don't have a good solution currently.  In the meantime, let me suggest a slight terminology change to the first 4 items that might reduce the confusion a bit:

Home
   Epidata API: COVIDcast Main Endpoint
   Epidata API: COVID-19 Trends and Impact Survey (CTIS) Endpoint
   Epidata API: Other Endpoints (COVID-19 and Other Diseases)

Or:

Epidata API Home
   COVIDcast Main Endpoint
   COVID-19 Trends and Impact Survey (CTIS) Endpoint
   Other Endpoints (COVID-19 and Other Diseases)

Either way, the first (home) item should be updated to clearly explain that 
  * COVIDcast is the name for all signals/indicators that are COVID-19 related.
  * Most COVIDcast indicators are accessed via the COVIDcast Main Endpoint, but some are accessed via the CTIS Endpoint, and others via Other Endpoints.
  * Epidata also provides access to signals related to other diseases, including flu, dengue and norovirus, which are accessed via the "Other" Endpoints node.

**Comment by ryantibs** [comment]
Thanks for the comprehensive analysis/reply!  Just to quickly chime in, that I like your second version: 

Epidata API Home
COVIDcast Main Endpoint
COVID-19 Trends and Impact Survey (CTIS) Endpoint
Other Endpoints (COVID-19 and Other Diseases)

and agree we should implement this (along with the explanation on the home page) ASAP.

**Comment by capnrefsmmat** [comment]
Just to throw a wrench in: the [CTIS page](https://cmu-delphi.github.io/delphi-epidata/symptom-survey/) is not about an API endpoint but about the survey itself. It's documentation of the survey questions, coding, data files, and so on. API access to the aggregate data is documented under the COVIDcast endpoint documentation, along with all the other usual data sources (like JHU and Change). That's why it got put under its own section.

So there's a CTIS section with survey documentation, and a separate CTIS page under the COVIDcast endpoint page that explains what aggregate data is available in the API.

**Comment by RoniRos** [comment]
Ok, so how about something like this:

Epidata API Home
____COVIDcast Main Endpoint
____Other Endpoints (COVID-19 and Other Diseases)
____Epidata API Development Guide
____New Endpoint Tutorial
The COVID-19 Trends and Impact Survey
Related Work

(The "____" are meant to be indentation / menu items).

The "Home" page should also be further corrected to reflect Alex's explanation.

**Comment by krivard** [comment]
Hi @RoniRos! Unearthing this as we now have a volunteer @LeonLu2 working on it.

It turns out the engine that turns our plaintext documentation into the API documentation website only supports three hierarchy levels.

We currently have

* Home
* COVIDcast Epidata API
  *  API Clients
  * COVIDcast Data Licensing
  * Data Sources and Signals
    *  COVID Act Now
    * COVID-19 Trends and Impact Survey
    * ...
    * USAFacts Cases and Deaths
  * Signal Changelog
  * Geographic Coding
  * ...
  * Inactive Signals
* COVID-19 Trends and Impact Survey
* Epidata API (Other ~Diseases~Endpoints)

Your recommendation requires a fourth level, which is not currently possible.

There is a fork of our documentation engine that claims to support an arbitrary numbers of levels, but we haven't been able to get it working.

We could:
* Keep trying with the fork
* Reorganize into three levels
* Try a different engine entirely

Thoughts?

**Comment by LeonLu2** [comment]
I think it's fine to try the fork and see if it provides every other features the same as the one we currently have. Or we can try to keep it in three levels which will make it easier for readers to navigate than four or higher levels. I don't think having a different engine would be the first choice and we might keep it as a last resort I guess?

**Comment by krivard** [comment]
On additional research, the fork is not ready to be used in production, and is part of an active development effort within Just The Docs.

Recommend the following 3-level organization for now:

```
Epidata API Home
COVIDcast Main Endpoint
Other Endpoints (COVID-19 and Other Diseases)
Epidata API Development Guide
New Endpoint Tutorial
The COVID-19 Trends and Impact Survey
Related Work
```

**Comment by RoniRos** [comment]
Sorry I am late.  Your recommendation looks good to me.

As part of our strategic / long term planning, I'd like to plan the transition to a more coherent view, per my original tirade above.  I will add it to out so-called "Fall 2022 OKRs" document.
