### ISSUE TITLE
Update package-lock file to point to cmu-delphi URL for delphi-cmu-buildtools

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#980]
Currently uses the URL in sgratzl's org:

https://github.com/cmu-delphi/delphi-epidata/blob/92e0027216100fa1b0e1240d1f886333c4fef4f1/package-lock.json#L9

the repo itself was already moved to this org, so that URL redirects here, but seeing it in package-lock gave us a bit of a start.

**Comment by dshemetov** [comment]
Since `package-lock.json` is generated by npm, it likely depends on the details of the developer's build system. Is there a chance @LeonLu2 used a local npm to build the documentation which put his local git settings into `package-lock.json` (instead of doing it in Docker, which I assume has an unconfigured git if it has one at all)? Just a guess.

**Comment by melange396** [comment]
i think your guess is spot on.  i also think we might wanna revert the changes to the package-lock file (other than the org swap for delphi-cmu-buildtools) unless @LeonLu2 thinks its better this way.  do we also want to pull in the newer changes from delphi-cmu-buildtools?

**Comment by LeonLu2** [comment]
Sorry, I think the change to the package-lock was unintentional. I can revert that :)
